Externals.cfg

This avoids any mishaps due to personal ownership of codebases and hopefully consolidates where work occurs. Externals affected by this are CCS_Configs, CMEPS, CAM, CIME, MPAS-Ocean, MPAS-SeaIce, and MPAS-Framework.

Ensure use of EarthWorksOrgs externals for develop branch

---

Externals.cfg

This affects the ccs_configs, cam, cmeps, cime, mpas-ocean, mpas-seaice, and mpas-framework externals and introduces no code or science changes.

Replace branches with tags for EarthWorksOrg externals

---

Externals.cfg

Unused code adds to the model size and complexity without benefit. This PR removes FMS, MOM, RTM, WW3, and WW3dev from Externals.cfg.

Limit EarthWorks externals to used components

---

Externals.cfg

To get the fully coupled model to run the mpas-framework external has been modified to match more closely to the MPAS-A framework.

Update mpas-framework to enable FullyCoupled compset

---

Externals.cfg

The externals' tag numbers are being incremented by one to incorporate recent Pull Requests.
Affected EarthWorksOrg externals and PR number:
- mpas-ocean    PR#1
- mpas-seaice   PR#1
- cime                 PR#1

Update externals to allow FullyCoupled compset to build with GNU

---

Externals.cfg

Incorporate changes in externals.
- cime: apply unoptimized GNU build flags to only 1 file in MPAS-SI
- ccs_configs: add Gust as a machine
- ewms_diags: point to the EarthWorksOrg fork instead

Update cime and ccs_configs externals for version 1 release

---

Externals.cfg

Advance the tags used in Externals.cfg to include development changes in MPAS-Ocean PR #2 as well as to match with the versions used in ESCOMP/CESM tag 'cesm2_3_beta11'.

Update externals with 'cesm2_3_beta11' tags and development changes

---

Externals.cfg

Advance the tags used in Externals.cfg to match with the versions used in ESCOMP/CESM tag 'cesm2_3_beta14'.

Update externals based on CESM tag 'cesm2_3_beta14'

---

Externals.cfg

Advance the tags used in Externals.cfg to match with the versions used in ESCOMP/CESM tag 'cesm2_3_alpha16d'.
EXCEPT: cam based on cam6_3_124 and not cam6_3_125

Update externals based on CESM tag 'cesm2_3_alpha16d' and add default files

---

Externals.cfg

- mpas-ocean: Update default io_type to "pnetcdf,cdf5" for oQU meshes
- mpas-seaice: Update default io_type to "pnetcdf,cdf5" for oQU meshes. Also fix intel compilation
- mpas-framework: Add logic to print PIO error messages when bad return values are given
- ccs_config: Add grids for river-runoff with mpas-ocean

Update mpas-* and ccs_configs externals

---

Externals.cfg

Urgent fix to allow new copies of EarthWorks to be fully checked out.
More info: [EarthWorksOrg/CAM Issue #9](https://github.com/EarthWorksOrg/CAM/issues/9), [EarthWorksOrg/CAM PR #10](https://github.com/EarthWorksOrg/CAM/pull/10)

Incorporate EarthWorksOrg/CAM PR #10

---

Externals.cfg

This PR moves CAM up to tag cam6_3_145 while adding a patch for NVHPC compilers, moving CIME up to tag cime6.0.0182, and brings in recent changes to mpas-seaice that fix Intel OneAPI builds.

Post cesm2_3_alpha17a Updates

---

Externals.cfg

Incorporate PRs and fixes in externals

EarthWorks v2.1.001 Branch

---

Externals.cfg

This PR incorporates changes in mpas-framework to the module names and changes to the buildlib scripts of mpas-ocean and mpas-seaice. All modules in mpas-framework source files begin with `MPASAOS` which the buidlib scripts replace (with `mpass` for mpas-seaice and `mpaso` for mpas-ocean) to create unique files and module names for mpas-seaice and mpas-ocean to use in their builds.
Fixes #36 but preserves compilation of 3 copies of "shared MPAS framework" routines.

Fix "Multiple definition" Error for GPU builds of compsets using multiple MPAS cores

---

Externals.cfg

Incorporate changes to EWOrg/ccs_config_cesm to use the `ncarenv/23.09` software stack and `nvhpc/24.3` on the Derecho supercomputer.

Update Derecho config to use NVHPC/24.3

---

Externals.cfg
cime_config/config_compsets.xml
cime_config/testlist_earthworks.xml
cime_config/testmods_dirs/earthworks/fullycoupled/user_nl_mpaso

Add definitions of compsets and tests so that typical EarthWorks cases can be run as CIME tests instead.
Testing instructions (in this thread): https://github.com/EarthWorksOrg/EarthWorks/pull/45#issuecomment-2118204061

Enable use of create_test workflow

---

Externals.cfg
cime_config/config_compsets.xml

F2000devEW copies F2000dev from CAM, but uses the mpas-seaice prescribed mode instead of CICE. CHAOS2000dev uses the cam_dev physics instead of CAM6. These compsets should allow GPU runs of MPAS-A dycore, PUMAS, and RRTMPG.

Add 2 compsets that use cam_dev physics

---

Externals.cfg
cime_config/testlist_earthworks.xml

These changes bring in a fix to namelist_defaults_cam.xml and aligns the testlist_earthworks.xml with the CPU tests described in the v2.2 (draft) release notes.
The changes to the `ew-rel` category make it so that the most complicated compset (CHAOS2000dev) is exercised at every supported EW resolution using an "exact restart" test.

Finalize before v2.2

---

Externals.cfg

This PR updates Externals.cfg to bring in the results of EarthWorksOrg/CAM PRs [#21](https://github.com/EarthWorksOrg/CAM/pull/21) and [#22](https://github.com/EarthWorksOrg/CAM/pull/22)

Incorporate CAM changes to ncdata and MPAS-A version

---

Externals.cfg

These changes allow the short-term and long-term archiver scripts to grab the correct restart and history files for these components. This moves the `create_test` framework closer to working and allowing EarthWorks to generate and compare against baselines.

Add config_archive.xml to MPAS-O and MPAS-SI

---

Externals.cfg

Bring in changes to EarthWorksOrg/ccs_config_cesm to address link step failures when building CAM with `pcols` > 2048.
Fix #56

Update ccs_configs to fix link step failures for high pcols builds

---

Externals.cfg

Duplicate #64 for the develop branch
This is duplicated due to the practice of using "release-{repo}-ew{X}.{Y}" tags in Externals.cfg on the EarthWorks main branch and "{repo}-ew{X}.{Y}.{Z}" in the develop branch. The reason for this PR will become more apparent once the Sub-PR is merged and tagged.

Bug Fix after v2.3 Release [develop]

---

Externals.cfg
cime_config/config_compsets.xml
cime_config/config_pes.xml
cime_config/testlist_allactive.xml
cime_config/testmods_dirs/allactive/defaultiomi/shell_commands

This is the first of a series of PRs that will update EarthWorks to more closely match the current development of ESCOMP/CESM.
This PR combines changes to use externals based on those used in the cesm2_3_beta17 tag and to update the cime_config folder with CESM changes.

Update externals based on ESCOMP/CESM tag 'cesm2_3_beta17'

---

.gitmodules
cime_config/config_compsets.xml
cime_config/config_pes.xml
cime_config/testlist_allactive.xml
cime_config/testlist_earthworks.xml
cime_config/testmods_dirs/allactive/defaultio/user_nl_mosart
cime_config/testmods_dirs/ew/no_gw_front/user_nl_cam

This PR combines changes to use externals based on those used in the cesm3_0_beta02 tag and to update the cime_config folder with CESM changes.
This PR is meant to be merged after #69

Update externals based on ESCOMP/CESM tag 'cesm3_0_beta02'

---

.gitmodules
cime_config/testlist_earthworks.xml
cime_config/testmods_dirs/ew/data_check/shell_commands
cime_config/testmods_dirs/ew/no_gw_front/user_nl_cam

This is a PR to incorporate other changes to EarthWorks. These include things like performance timers and input file changes.
Please suggest any other changes you can think of!
NOTE: the code in this PR may not fetch cleanly until all Sub-PRs are merged and this PR is moved out of draft.

Other changes after cesm3_0_beta02 update

---

.gitmodules

modify to checkout the update/ocean branches of
CMEPS
mpas-ocean
mpas-seaice
mpas-framework
This is part of a package of PRs for branches named update/ocean:
EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)
EarthWorksOrg /mpas-seaice PR [#17](https://github.com/EarthWorksOrg/mpas-seaice/pull/17)
EarthWorksOrg /mpas-framework PR [#10](https://github.com/EarthWorksOrg/mpas-framework/pull/10)
EarthWorksOrg /CMEPS PR [#12](https://github.com/EarthWorksOrg/CMEPS/pull/12)
EarthWorksOrg/EarthWorks PR [#75](https://github.com/EarthWorksOrg/EarthWorks/pull/75) (incorporates above)

Checkout update/ocean branches

---

.gitmodules
cime_config/testlist_earthworks.xml

Use the newest nvhpc/24.9 stack on Derecho by updating ccs_configs. Since nvhpc/24.9 fixes a restart issue with CAM-MPAS, tests are added to check restarts with the FHS94 and CHAOS2000dev compsets in the `ew-pr` category.
This PR fixes #21

Upgrade Derecho nvhpc software stack to 24.9, add restart tests

---

.gitmodules

This PR brings switches the mpas external in CAM to use an updated OpenACC version that works for simple physics compsets. This re-enables MPAS-A OpenACC that was removed in #57.
More complicated test cases on GPUs like F2000climo and CHAOS2000dev now fail to complete with these changes. Answers beginning diverging from previous results and the runs either fail to finish within allotted time or crash due to "NaN detected in the 'w' field". These compsets successfully complete on GPUs if the CPU-only [ew-develop-noacc](https://github.com/EarthWorksOrg/MPAS-Model/tree/ew-develop-noacc) MPAS-A branch is used instead.
CPU results are unaffected in CAM-MPAS with these changes.

Re-enable MPAS-A OpenACC, improve GPU answer differences.

---

.gitmodules

MPAS Ocean and Seaice have been modified so that the logging of standard output go to the proper uniquely stamped log file instead of the generic fort.*
This is an update to .gitmodules to get the ocean/seaice/logging branch of the ocean and seaice components.
The ew-pr test suite with the intel compiler has been run and works.

Fix standard output logging of ocean and seaice.

---

.gitmodules

Basically reverts PR #80. This PR closes #90, but would re-open #21 since nvhpc/24.9 fixes restartability.

Revert to nvhpc/24.3 software stack on Derecho

---

.gitmodules

This modification lets the user get the BFBrestartability branches for mpas-ocean and mpas-seaice, which have established bit-for-bit restartability for the restart files and some of the diagnostic output for those components.

BFB restartability for mpas-ocean and -seaice

---

.gitmodules

Fixes loop bounds that cause CAM-MPAS runs in EarthWorks to fail if built with DEBUG=true. This applies to CPU and GPU runs.
Closes #103.

Fix loop bounds in EWOrg/MPAS-Model for DEBUG=true runs

---

cime_config/config_compsets.xml

At ewm-2.4.006 we are based on cesm3_0_beta05 which allows CAM70 and CLM50%SP to be used together. Updating to cesm3_0_beta06 showed an incompatibility with dust emission settings for compsets defined with '..._CAM70_CLM50%SP...' that prevents cases/tests from completing `case.setup`.
Our compsets that nominally track F2000dev have had a different land version for a while, this PR addresses that.

Update EW compsets, use CLM60 in F2000dev-like compsets

---

.gitmodules

CAM is updated in this PR to remove changes associated with EarthWorks-specific PRs.

Better align EWOrg/CAM with upstream tag cam6_4_048

---

.gitmodules

Revert changes made to EarthWorksOrg/ccs_config_cesm during the EarthWorks v2.5 release. After this PR, ccs_config_cesm will largely match its upstream.
This PR works best if merged alongside or before #124. Together, they show a marked reduction in memory used by EarthWorks runs compiled with NVHPC 24.9+ on Derecho.
Fixes #21

Use NVHPC v24.11 stack on Derecho

---

.gitmodules
cime_config/testlist_earthworks.xml

This removes the MPASO_OPENACC_BUILD_FLAGS from ccs_configs, comments out changes in cime to pass OpenACC flags to the MPAS-O build, and comments out the CMPASO GPU test.
Some code is commented and not deleted out as I anticipate other changes that may re-enable MPAS-O on GPUs.

Undo or revert changes for MPAS-O on GPU
